kubectl:
  # update to the latest supported k8s releases
  # ref: https://kubernetes.io/releases
  versions:
    - v1.25.4
    - v1.24.8
    - v1.23.14

helm:
  version: v3.10.2

kustomize:
  version: v4.5.7

kubeconform:
  version: v0.5.0
